version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.php
    ports:
      - "80:80"
    depends_on:
      - db
    volumes:
      - .:/var/www/html 

  ai-api:
    build:
      context: .
      dockerfile: Dockerfile.python
    ports:
      - "8000:8000"

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: visionflow_db
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql 

volumes:
  db_data: